config/routes.rb
Rails.application.routes.draw do
  # Devise routings
  devise_for :users

  # Authenticated root path
  authenticated :user do
    root :to => "dashboard#dashboard", :as => "user_authenticated_root"
  end

  resource :me, only: [:show, :edit, :update]
  resource :team, only: [:show, :edit, :update]

  namespace :team do
    resources :projects
  end

  resources :members, only: [:index, :show, :new, :create], controller: :users do
    resources :posts, only: :index, module: :users
  end

  resources :posts, only: [:show, :new, :create] do
    resources :stars, only: :create, controller: 'posts/stars' do
      delete :destroy, on: :collection
    end
  end

  namespace :me do
    namespace :posts do
      resources :stars, only: :index
    end
    resources :posts, only: [:index, :edit, :update, :destroy]
  end

  # Unauthenticated routings
  get  "/*id",to: 'pages#show', as: :page, format: false, constraints: HighVoltage::Constraints::RootRoute

  # Root path
  root 'pages#home'
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id             :integer          not null, primary key
#  team_id        :integer          not null
#  client_name    :string           not null
#  project_name   :string           not null
#  status         :integer          default(0), not null
#  description    :text
#  scheduled_time :integer
#  actual_time    :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
# Indexes
#
#  index_projects_on_team_id  (team_id)
#
# Foreign Keys
#
#  fk_rails_...  (team_id => teams.id)
#

class Project < ApplicationRecord
  belongs_to :team
  has_many :post_details, dependent: :destroy

  enum status: { draft: 0, sales: 10, review: 20, dev: 30, ops: 40, maintenance: 50, closed: 999 }

  validates :client_name, presence: true
  validates :project_name, presence: true
  validates :status, presence: true

  def name
    client_name + ' / ' + project_name
  end

  def described_users
    post_details.map{ |d| d.post.user }.uniq
  end
end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id           :integer          not null, primary key
#  name         :string           not null
#  access_token :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_teams_on_access_token  (access_token) UNIQUE
#  index_teams_on_name          (name) UNIQUE
#

class Team < ApplicationRecord
  has_many :projects
  has_many :users

  validates :name, presence: true, uniqueness: true
  validates :access_token, uniqueness: true

  before_validation :set_access_token

  def posts
    Post.includes(:user).where(user_id: users.ids)
  end

  def post_activities_rate
    max = users.size * number_of_days_created
    (posts.size.to_f / max * 100).round(1)
  end

  def most_starred_post
    max = posts.maximum(:stars_count)
    posts.find_by('stars_count >= ?', max)
  end

  private

  def set_access_token
    self.access_token = access_token.presence || SecureRandom.hex
  end

  def number_of_days_created
    (Date.current - created_at.to_date).to_i
  end
end

app/controllers/team/projects_controller.rb
class Team::ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = current_user.team.projects
  end

  def show
  end

  def new
    @project = current_user.team.projects.new
  end

  def edit
  end

  def create
    @project = current_user.team.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to [:team, @project], notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to [:team, @project], notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to team_projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def project_params
    params.require(:project).permit(:client_name, :project_name, :status, :description, :scheduled_time, :actual_time)
  end

  def set_project
    @project = current_user.team.projects.find(params[:id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to team_path, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_team
    @team = current_user.team
  end

  def team_params
    params.require(:team).permit(:name, :access_token)
  end
end

app/views/team/projects/_form.html.slim
- url = @project.new_record? ? team_projects_path : team_project_path
= simple_form_for @project, url: url do |f|
  - if @project.errors.any?
    #error_explanation
      pre
        = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
        ul
          - @project.errors.full_messages.each do |message|
            li = message
  .row
    .col.s12
      .row
        .input-field.col.s12.m12
          = f.input :client_name, class: "materialize-text",label_html: { class: "active" }
      .row
        .input-field.col.s12.m12
          = f.input :project_name, class: "materialize-text",label_html: { class: "active" }
      .row
        .input-field.col.s12.m12
          = f.input :description, class: "materialize-text", label_html: { class: "active" }
      .row
        .input-field.col.s6.m6
          = f.input :scheduled_time, icon: 'access_time'
        .input-field.col.s6.m6
          = f.input :actual_time, icon: 'access_time'
      .row
        .input-field.col.s6.m3
          = f.input :status, as: :select, collection: Project.statuses.keys.to_a, include_blank: false, label: false, icon: 'settings'
      .row
        .input-field.col.s3
          = f.button :submit

app/views/team/projects/edit.html.slim
h4 Editing project

== render 'form'

= link_to 'Back', team_projects_path

app/views/team/projects/index.html.slim
br
br
div class="row"
  div id="admin" class="col s12"
    div class="card material-table"
      div class="table-header"

        h5 Projects
        .actions data-turbolinks="false"
          a.search-toggle.waves-effect.btn-flat.nopadding href="#"
            i.material-icons search

      table#dttb.table
        thead
          tr
            th width="30%" Name
            th width="30%" Status
            th

        tbody
          - @projects.each do |project|
            tr
              td = project.project_name
              td = project.status
              td.right-align
                = link_to 'Show ', team_project_path(project)
                = link_to ' Edit ', edit_team_project_path(project)
                = link_to ' Destroy', team_project_path(project), data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/team/projects/new.html.slim
h4 New project

== render 'form'

= link_to 'Back', team_projects_path

app/views/team/projects/show.html.slim
article
  .row
    .col.s12.m12
      h4
        = @project.name
      .card
        .card-content
          p
            = "created at: #{@project.created_at}"
          p
            = "updated at: #{@project.updated_at}"
        .card-tabs
          ul.tabs.tabs-fixed-width
            li.tab
              a.active href="#details"  Details
            li.tab
              a href="#contents" Contents
            li.tab
              a href="#comments"  Comments
            li.indicator style=("right: -12px; left: 184px;")
        .card-content.grey.lighten-4 style=("word-break: break-word;")
          #details.active style=""
            .row
              .card-panel.hoverable
                span.card-title
                  = @project.project_name
                  = @project.status
                p
                  = "Client: #{@project.client_name}"
                span
                  i.material-icons access_time
                  = "scheduled: #{@project.scheduled_time} hours"
                span
                  i.material-icons access_time
                  = "actual: #{@project.actual_time} hours"

          #contents style=("display: none;")
            .row
              .card-panel.hoverable
                span.card-title
                  | Description
                p
                  = @project.description

          #comments style=("display: none;")  This is comment.


= link_to 'Edit', edit_team_project_path(@project)
'|
= link_to 'Back', team_projects_path