config/routes.rb
Rails.application.routes.draw do
  # Devise routings
  devise_for :users

  # Authenticated root path
  authenticated :user do
    root :to => "dashboard#dashboard", :as => "user_authenticated_root"
  end

  resource :me, only: [:show, :edit, :update]
  resource :team, only: [:show, :edit, :update]

  namespace :team do
    resources :projects
  end

  resources :members, only: [:index, :show, :new, :create], controller: :users do
    resources :posts, only: :index, module: :users
  end

  resources :posts, only: [:show, :new, :create] do
    resources :stars, only: :create, controller: 'posts/stars' do
      delete :destroy, on: :collection
    end
  end

  namespace :me do
    namespace :posts do
      resources :stars, only: :index
    end
    resources :posts, only: [:index, :edit, :update, :destroy]
  end

  # Unauthenticated routings
  get  "/*id",to: 'pages#show', as: :page, format: false, constraints: HighVoltage::Constraints::RootRoute

  # Root path
  root 'pages#home'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  team_id                :integer          not null
#  first_name             :string
#  last_name              :string
#  username               :string           default(""), not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  role                   :integer          default(0)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_team_id               (team_id)
#
# Foreign Keys
#
#  fk_rails_...  (team_id => teams.id)
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :stars
  has_many :starred_posts, through: :stars, source: :post

  belongs_to :team
  accepts_nested_attributes_for :team

  def today_post?
    posts.exists?(created_at: Time.current.all_day)
  end

  def starred?(post)
    stars.exists?(post: post)
  end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :set_user

  def index
    @posts = @user.posts.order(created_at: :desc)
  end

  private

  def set_user
    @user = current_user.team.users.find(params[:member_id])
  end
end

app/controllers/users_controller.rb
# NOTE: Defined 'members' by routes.rb

class UsersController < ApplicationController
  before_action :set_user, only: :show

  def index
    @users = current_user.team.users
  end

  def show; end

  def new
    @user = current_user.team.users.new
  end

  def create
    @user = current_user.team.users.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to member_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def set_user
    @user = current_user.team.users.find(params[:id])
  end
end

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions' && !current_user.present?
  | Already a Member? 
  = link_to "Log In", new_session_path(resource_name)
br
- if devise_mapping.registerable? && controller_name != 'registrations'
  | Not A Member? 
  = link_to "Sign Up", new_registration_path(resource_name)
br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  | Forgot 
  = link_to "Password?", new_password_path(resource_name)
br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't Receive Confirmation Instructions?", new_confirmation_path(resource_name)
br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't Receive Unlock Instructions?", new_unlock_path(resource_name)
br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
- if controller_name == 'registrations' && current_user.present?
  = link_to "Cancel My Account", registration_path(resource_name), data: { confirm: "Are You Sure you want to Delete Your Account?",  method: :delete }, class: "btn waves-effect red"
 