config/routes.rb
Rails.application.routes.draw do
  # Devise routings
  devise_for :users

  # Authenticated root path
  authenticated :user do
    root :to => "dashboard#dashboard", :as => "user_authenticated_root"
  end

  resource :me, only: [:show, :edit, :update]
  resource :team, only: [:show, :edit, :update]

  namespace :team do
    resources :projects
  end

  resources :members, only: [:index, :show, :new, :create], controller: :users do
    resources :posts, only: :index, module: :users
  end

  resources :posts, only: [:show, :new, :create] do
    resources :stars, only: :create, controller: 'posts/stars' do
      delete :destroy, on: :collection
    end
  end

  namespace :me do
    namespace :posts do
      resources :stars, only: :index
    end
    resources :posts, only: [:index, :edit, :update, :destroy]
  end

  # Unauthenticated routings
  get  "/*id",to: 'pages#show', as: :page, format: false, constraints: HighVoltage::Constraints::RootRoute

  # Root path
  root 'pages#home'
end

app/views/partials/components/_badges.html.slim
h3 Badges


h5 Badges

.collection
  a.collection-item href="#!" 
    span.badge> 1
    | Alan
  a.collection-item href="#!" 
    span.new.badge> 4
    | Alan
  a.collection-item href="#!"  Alan
  a.collection-item href="#!" 
    span.badge> 14
    | Alan

br
h5 Badges in Dropdown
ul#dropdown2.dropdown-content
  li
    a href="#!" 
      | one
      span.badge 1
  li
    a href="#!" 
      | two
      span.new.badge 1
  li
    a href="#!"  three
a.btn.dropdown-button data-activates="dropdown2" href="#!" 
  | Dropdown
  i.mdi-navigation-arrow-drop-down.right

br
br
h5 Badges in Collapsibles
ul.collapsible data-collapsible="accordion" 
  li
    .collapsible-header
      span.new.badge 4
      i.material-icons filter_drama
      span First
    .collapsible-body
      p Lorem ipsum dolor sit amet.
  li
    .collapsible-header
      span.badge 1
      i.material-icons place
      span Second
    .collapsible-body
      p Lorem ipsum dolor sit amet.

app/views/partials/components/_breadcrumbs.slim
h5 Breadcrumbs
nav
  .nav-wrapper
    .col.s12
      a.breadcrumb href="#!"  First
      a.breadcrumb href="#!"  Second
      a.breadcrumb href="#!"  Third

app/views/partials/components/_buttons.html.slim
.fixed-action-btn.horizontal
  a.btn-floating.btn-large.red
    i.material-icons add
  ul
    li
      = link_to new_post_path, class: "btn-floating red" do
        i.material-icons note_add
    li
      = link_to new_member_path, class: "btn-floating yellow.darken-1" do
        i.material-icons person_add
    li
      = link_to new_team_project_path, class: "btn-floating purple" do
        i.material-icons add_to_queue
    li
      a.btn-floating.blue
        i.material-icons attach_file

app/views/partials/components/_cards.html.slim
h3 Cards

h5 Basic card

.row
  .col.s12.m6
    .card.blue-grey.darken-1
      .card-content.white-text
        span.card-title Card Title
        p
          | I am a very simple card. I am good at containing small bits of information.
          | I am convenient because I require little markup to use effectively.
      .card-action
        a href="#"  This is a link
        a href="#"  This is a link

h5 Image card

.row
  .col.s12.m7
    .card
      .card-image
        img src="http://materializecss.com/images/sample-1.jpg" /
        span.card-title Card Title
      .card-content
        p
          | I am a very simple card. I am good at containing small bits of information.
          | I am convenient because I require little markup to use effectively.
      .card-action
        a href="#"  This is a link


.row
  .col.s12.m6
    .card
      .card-image
        img src="http://materializecss.com/images/sample-1.jpg" /
        span.card-title Card Title
        a.btn-floating.halfway-fab.waves-effect.waves-light.red
          i.material-icons add
      .card-content
        p I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.

app/views/partials/components/_forms.html.slim
h3 Forms

h5 Input fields
.row
  form.col.s12
    .row
      .input-field.col.s6
        input#first_name.validate placeholder="Placeholder" type="text" /
        label for="first_name"  First Name
      .input-field.col.s6
        input#last_name.validate type="text" /
        label for="last_name"  Last Name
    .row
      .input-field.col.s12
        input#disabled.validate disabled="" type="text" value=("I am not editable") /
        label for="disabled"  Disabled
    .row
      .input-field.col.s12
        input#password.validate type="password" /
        label for="password"  Password
    .row
      .input-field.col.s12
        input#email1.validate type="email" /
        label for="email1"  Email
    .row
      .col.s12
        | This is an inline input field:
        .input-field.inline
          input#email2.validate type="email" /
          label data-error="wrong" data-success="right" for="email2"  Email


h5 Prefilling Text Inputs
.row
  .input-field.col.s6
    input#first_name2.validate type="text" value="Alvin" /
    label.active for="first_name2"  First Name


h5 Icon Prefixes
.row
  form.col.s12
    .row
      .input-field.col.s6
        i.material-icons.prefix account_circle
        input#icon_prefix.validate type="text" /
        label for="icon_prefix"  First Name
      .input-field.col.s6
        i.material-icons.prefix phone
        input#icon_telephone.validate type="tel" /
        label for="icon_telephone"  Telephone


h5 Custom Error or Success Messages
.row
  form.col.s12
    .row
      .input-field.col.s12
        input#email.validate type="email" /
        label data-error="wrong" data-success="right" for="email"  Email


h5 Textarea
.row
  form.col.s12
    .row
      .input-field.col.s12
        textarea#textarea1.materialize-textarea
        label for="textarea1"  Textarea


.row
  form.col.s12
    .row
      .input-field.col.s6
        i.material-icons.prefix mode_edit
        textarea#icon_prefix2.materialize-textarea
        label for="icon_prefix2"  First Name


h5 Select

.input-field.col.s12
  select
    option disabled="" selected="" value=""  Choose your option
    option value="1"  Option 1
    option value="2"  Option 2
    option value="3"  Option 3
  label Materialize Select
.input-field.col.s12
  select multiple="" 
    option disabled="" selected="" value=""  Choose your option
    option value="1"  Option 1
    option value="2"  Option 2
    option value="3"  Option 3
  label Materialize Multiple Select
.input-field.col.s12
  select multiple="" 
    optgroup label=("team 1") 
      option value="1"  Option 1
      option value="2"  Option 2
    optgroup label=("team 2") 
      option value="3"  Option 3
      option value="4"  Option 4
  label Optgroups
.input-field.col.s12.m6
  select.icons
    option disabled="" selected="" value=""  Choose your option
    option.circle data-icon="http://materializecss.com/images/sample-1.jpg" value=""  example 1
    option.circle data-icon="http://materializecss.com/images/office.jpg" value=""  example 2
    option.circle data-icon="http://materializecss.com/images/yuna.jpg" value=""  example 3
  label Images in select
.input-field.col.s12.m6
  select.icons
    option disabled="" selected="" value=""  Choose your option
    option.left.circle data-icon="http://materializecss.com/images/sample-1.jpg" value=""  example 1
    option.left.circle data-icon="http://materializecss.com/images/office.jpg" value=""  example 2
    option.left.circle data-icon="http://materializecss.com/images/yuna.jpg" value=""  example 3
  label Images in select
label Browser Select
select.browser-default
  option disabled="" selected="" value=""  Choose your option
  option value="1"  Option 1
  option value="2"  Option 2
  option value="3"  Option 3



label Materialize Disabled
select disabled="" 
  option disabled="" selected="" value=""  Choose your option
  option value="1"  Option 1
  option value="2"  Option 2
  option value="3"  Option 3
label Browser Disabled
select.browser-default disabled="" 
  option disabled="" selected="" value=""  Choose your option
  option value="1"  Option 1
  option value="2"  Option 2
  option value="3"  Option 3



h5 Radio Buttons

form action="#" 
  p
    input#test-input0 name="group1" type="radio" /
    label for="test-input0"  Red
  p
    input#test-input1 name="group1" type="radio" /
    label for="test-input1"  Yellow
  p
    input#test-input2.with-gap name="group1" type="radio" /
    label for="test-input2"  Green
  p
    input#test-input3 disabled="disabled" name="group1" type="radio" /
    label for="test-input3"  Brown

  p
    input#test-input4.with-gap checked="" name="group3" type="radio" /
    label for="test-input4"  Red

br
h5 Checkbox
form action="#" 
  p
    input#test-input5 type="checkbox" /
    label for="test-input5"  Red
  p
    input#test-input6 checked="checked" type="checkbox" /
    label for="test-input6"  Yellow
  p
    input#filled-in-box.filled-in checked="checked" type="checkbox" /
    label for="filled-in-box"  Filled in
  p
    input#indeterminate-checkbox type="checkbox" /
    label for="indeterminate-checkbox"  Indeterminate Style
  p
    input#test-input7 checked="checked" disabled="disabled" type="checkbox" /
    label for="test-input7"  Green
  p
    input#test-input8 disabled="disabled" type="checkbox" /
    label for="test-input8"  Brown


h5 Switch
/! Switch
.switch
  label
    | Off
    input type="checkbox" /
    span.lever
    | On
/! Disabled Switch
.switch
  label
    | Off
    input disabled="" type="checkbox" /
    span.lever
    | On

h5 Files
form action="#" 
  .file-field.input-field
    .btn
      span File
      input multiple="" type="file" /
    .file-path-wrapper
      input.file-path.validate placeholder=("Upload one or more files") type="text" /

br
h5 no-Ui slider
#range-slider

javascript:
   var slider = document.getElementById('range-slider');
   noUiSlider.create(slider, {
   start: [20, 80],
   connect: true,
   step: 1,
   range: {
     'min': 0,
     'max': 100
   },
   format: wNumb({
     decimals: 0
   })
   });

br
h5 HTML5 Slider
form action="#" 
  p.range-field
    input#test-input9 max="100" min="0" type="range" /

h5 Date Picker
input type="text" class="datepicker"

javascript:
  $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });
       
h5 Time Picker
input type="text" class="timepicker" 

javascript:
  $('.timepicker').pickatime({
    default: 'now', // Set default time
    fromnow: 0,       // set default time to * milliseconds from now (using with default = 'now')
    twelvehour: false, // Use AM/PM or 24-hour format
    donetext: 'OK', // text for done-button
    cleartext: 'Clear', // text for clear-button
    canceltext: 'Cancel', // Text for cancel-button
    autoclose: false, // automatic close timepicker
    ampmclickable: true, // make AM PM clickable
    aftershow: function(){} //Function for after opening timepicker  
  });


h5 Character Counter
.row
  form.col.s12
    .row
      .input-field.col.s6
        input#input_text data-length="10" type="text" /
        label for="input_text"  Input text
    .row
      .input-field.col.s12
        textarea#textarea0.materialize-textarea data-length="120" 
        label for="textarea1"  Textarea



h5 Autocomplete
.row
  .col.s12
    .row
      .input-field.col.s12
        i.material-icons.prefix textsms
        input#autocomplete-input.autocomplete type="text" /
        label for="autocomplete-input"  Autocomplete

javascript:
  $('input.autocomplete').autocomplete({
    data: {
      "Apple": null,
      "Microsoft": null,
      "Google": 'http://placehold.it/250x250'
    },
    limit: 20, // The max amount of results that can be shown at once. Default: Infinity.
    onAutocomplete: function(val) {
      // Callback function when value is autcompleted.
    },
    minLength: 1, // The minimum length of the input for the autocomplete to start. Default: 1.
  });

app/views/partials/components/_modal.html.slim
h3 Modal

button.btn data-target="modal1"  Modal 1
button.btn data-target="modal2"  Modal 2
button.btn data-target="modal3"  Modal 3


/! Modal Trigger
a.waves-effect.waves-light.btn href="#modal1" data-turbolinks="false"  Modal
/! Modal Structure
#modal1.modal
  .modal-content
    h4 Modal Header
    p A bunch of text
  .modal-footer
    a.modal-action.modal-close.waves-effect.waves-green.btn-flat href="#!"  Agree
/! Modal Trigger
a.modal-trigger.waves-effect.waves-light.btn href="#modal2" data-turbolinks="false"  Modal
/! Modal Structure
#modal2.modal.modal-fixed-footer
  .modal-content
    h4 Modal Header
    p A bunch of text
  .modal-footer
    a.modal-action.modal-close.waves-effect.waves-green.btn-flat href="#!"  Agree
/! Modal Trigger
a.waves-effect.waves-light.btn href="#modal3" data-turbolinks="false"  Modal
/! Modal Structure
#modal3.modal.bottom-sheet
  .modal-content
    h4 Modal Header
    p A bunch of text
  .modal-footer
    a.modal-action.modal-close.waves-effect.waves-green.btn-flat href="#!"  Agree

app/views/partials/components/_stars.html.slim
= link_to 'javascript:void(0)', class: 'right js-star-toggle', data: { id: post.id } do
  i.small.material-icons.js-star style=('color: #F9A825;')
    = current_user.starred?(post.id) ? 'star' : 'star_border'

app/views/partials/components/_tabs.html.slim
br/
h5
  | Variable Width Tabs
  span Default
ul.tabs.tab-demo.z-depth-1
  li.tab
    a href="#test-tabs16"  Test 1
  li.tab
    a.active href="#test-tabs17"  Test 2
  li.tab
    a href="#test-tabs18"  Test 3
  li.tab
    a href="#test-tabs19"  Test 4
#test-tabs16.col.s12
  p Test 1
#test-tabs17.col.s12
  p Test 2
#test-tabs18.col.s12
  p Test 3
#test-tabs19.col.s12
  p Test 4

br/
h5
  | Fixed Width Tabs
  span
    | Add the
    code.language-markup .tabs-fixed-width
    | class
ul.tabs.tabs-fixed-width.tab-demo.z-depth-1
  li.tab
    a href="#test-tabs1"  Test 1
  li.tab
    a.active href="#test-tabs2"  Test 2
  li.tab.disabled
    a href="#test-tabs3"  Disabled Tab
  li.tab
    a href="#test-tabs4"  Test 4
  li.tab
    a href="#test-tabs0"  Test 5
#test-tabs1.col.s12
  p Test 1
#test-tabs2.col.s12
  p Test 2
#test-tabs3.col.s12
  p Test 3
#test-tabs4.col.s12
  p Test 4
#test-tabs0.col.s12
  p Test 5
br/
h5
  | Scrollable Tabs
  span Tabs automatically become scrollable
ul.tabs.tab-demo.z-depth-1
  li.tab
    a href="#test-tabs5"  Test 1
  li.tab
    a.active href="#test-tabs6"  Test 2
  li.tab
    a href="#test-tabs7"  Test 4
  li.tab
    a href="#test-tabs8"  Test 1
  li.tab
    a.active href="#test-tabs9"  Test 2
  li.tab.disabled
    a href="#test-tabs10"  Disabled Tab
  li.tab
    a href="#test-tabs11"  Test 4
  li.tab
    a href="#test-tabs12"  Test 1
  li.tab
    a.active href="#test-tabs13"  Test 2
  li.tab.col.s3.disabled
    a href="#test-tabs14"  Disabled Tab
  li.tab.col.s3
    a href="#test-tabs15"  Test 4
#test-tabs5.col.s12
  p Test 5
#test-tabs6.col.s12
  p Test 6
#test-tabs7.col.s12
  p Test 7
#test-tabs8.col.s12
  p Test 8
#test-tabs9.col.s12
  p Test 9
#test-tabs10.col.s12
  p Test 10
#test-tabs11.col.s12
  p Test 11
#test-tabs12.col.s12
  p Test 12
#test-tabs13.col.s12
  p Test 13
#test-tabs14.col.s12
  p Test 14
#test-tabs15.col.s12
  p Test 15