config/routes.rb
Rails.application.routes.draw do
  # Devise routings
  devise_for :users

  # Authenticated root path
  authenticated :user do
    root :to => "dashboard#dashboard", :as => "user_authenticated_root"
  end

  resource :me, only: [:show, :edit, :update]
  resource :team, only: [:show, :edit, :update]

  namespace :team do
    resources :projects
  end

  resources :members, only: [:index, :show, :new, :create], controller: :users do
    resources :posts, only: :index, module: :users
  end

  resources :posts, only: [:show, :new, :create] do
    resources :stars, only: :create, controller: 'posts/stars' do
      delete :destroy, on: :collection
    end
  end

  namespace :me do
    namespace :posts do
      resources :stars, only: :index
    end
    resources :posts, only: [:index, :edit, :update, :destroy]
  end

  # Unauthenticated routings
  get  "/*id",to: 'pages#show', as: :page, format: false, constraints: HighVoltage::Constraints::RootRoute

  # Root path
  root 'pages#home'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id                 :integer          not null, primary key
#  user_id            :integer          not null
#  published_at       :datetime         not null
#  unknown_content    :text
#  impression_content :text
#  status             :integer          default("draft"), not null
#  stars_count        :integer          default(0), not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Post < ApplicationRecord
  has_many :post_details, inverse_of: :post, dependent: :destroy
  has_many :stars, dependent: :destroy
  accepts_nested_attributes_for :post_details, allow_destroy: true, reject_if: :all_blank

  belongs_to :user

  enum status: %i[draft closed published]

  validates :published_at, presence: true
  validates :status, presence: true
  validates :stars_count, presence: true
end

app/controllers/me/posts/stars_controller.rb
class Me::Posts::StarsController < ApplicationController

  def index
    @posts = current_user.starred_posts
      .includes(:user)
  end
end

app/controllers/me/posts_controller.rb
class Me::PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]

  helper_method :current_post_hit

  def index
    @posts = current_user.posts
  end

  def edit
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to me_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # TODO: Move another
  def current_post_hit
    hit = cookies['post_hit'].to_i
    hit += 1
    cookies['post_hit'] = hit
    hit
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:published_at, :unknown_content, :impression_content, :status, post_details_attributes: [:id, :project_id, :spent_time, :content, :_destroy])
  end
end

app/controllers/posts/stars_controller.rb
class Posts::StarsController < ApplicationController
  before_action :set_post

  def create
    star = current_user.stars.new(post: @post)

    if star.save
      render status: :ok, json: { id: @post.id }
    else
      head :bad_request
    end
  end

  def destroy
    star = current_user.stars.find_by(post: @post)
    star.destroy
    render status: :ok, json: { id: @post.id }
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: :show

  def show; end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_post
    @post = current_user.team.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:published_at, :unknown_content, :impression_content, :status, post_details_attributes: [:id, :project_id, :spent_time, :content, :_destroy])
  end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :set_user

  def index
    @posts = @user.posts.order(created_at: :desc)
  end

  private

  def set_user
    @user = current_user.team.users.find(params[:member_id])
  end
end

app/views/posts/_post_detail_fields.html.slim
.nested-fields.field
  .row.card-panel.grey.lighten-5.hoverable
    .col.s12
      = link_to_remove_association f, class: 'right' do
        i.material-icons remove_circle
      .row
        .input-field.col.s12.m12
          = f.input :project_id, collection: current_user.team.projects, label_method: :name, value_method: :id, icon: 'business'
      .row
        .input-field.col.s6.m3
          = f.input :spent_time, collection: 1..24, icon: 'access_time'
      .row
        .input-field.col.s12.m12
          = f.input :content, class: "materialize-textarea", label_html: { class: "active" }, icon: 'description'

app/views/posts/edit.html.slim
h4 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/index.html.slim
br
br
div class="row"
  div id="admin" class="col s12"
    div class="card material-table"
      div class="table-header"

        h5 Posts
        .actions data-turbolinks="false"
          a.search-toggle.waves-effect.btn-flat.nopadding href="#"
            i.material-icons search

      table#dttb.table
        thead
          tr
            th width="30%"Title
            th Body
            th width="100px" Published
            th

        tbody
          - @posts.each do |post|
            tr
              td = post.title
              td = post.body
              td = post.published
              td.right-align
                = link_to 'Show ', post
                = link_to ' Edit ', edit_post_path(post)
                = link_to ' Destroy', post, data: {:confirm => 'Are you sure?'}, :method => :delete

.fixed-action-btn
  a#newpost.waves-effect.waves-light.btn.btn-floating.btn-large.cyan href="#{new_post_path}"
    i.large.material-icons add

/! Tap Target Structure
.tap-target.newpost.cyan data-activates="newpost"
  .tap-target-content
    h5 Start posting
    p Tell me what not working

- if current_post_hit <= 1
  javascript:
    $('.tap-target.newpost').tapTarget('open');

app/views/posts/new.html.slim
h3 New your post

= simple_form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      pre
        = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
        ul
          - @post.errors.full_messages.each do |message|
            li = message

  .row
    .col.s12
      .row
        .input-field.col.s8.m4
          = f.input :published_at, as: :string, input_html: { class: "datepicker" }, label_html: { class: "active" }, icon: 'today'

      .divider
      h4 Details
      .js-cocoon
        = f.simple_fields_for :post_details do |post_detail|
          = render 'post_detail_fields', f: post_detail
        .row.links.right-align
          = link_to_add_association f, :post_details, class: 'btn waves-effect waves-light purple' do
            i.material-icons.left note_add
            | Add
      .divider
      br

      .row
        .input-field.col.s12.m12
          = f.input :unknown_content, class: "materialize-textarea", label_html: { class: "active" }, icon: 'message'
      .row
        .input-field.col.s12.m12
          = f.input :impression_content, class: "materialize-textarea", label_html: { class: "active" }, icon: 'message'
      .row
        .input-field.col.s6.m3
          = f.input :status, as: :select, collection: Post.statuses.keys.to_a, include_blank: false, label: false, icon: 'settings'

      .row
        .input-field.col.s3
          = f.button :submit

= link_to 'Back', me_posts_path

app/views/posts/show.html.slim
article
  .row
    .col.s12.m12
      h4
        = "#{@post.user.username.presence} Post"
      .card
        .card-content
          = render partial: 'partials/components/stars', locals: { post: @post }
          p
            = "published at: #{@post.published_at}"
          p
            = "updated at: #{@post.updated_at}"
        .card-tabs
          ul.tabs.tabs-fixed-width
            li.tab
              a.active href="#details"  Details
            li.tab
              a href="#contents" Contents
            li.tab
              a href="#comments"  Comments
            li.indicator style=("right: -12px; left: 184px;")
        .card-content.grey.lighten-4 style=("word-break: break-word;")
          #details.active style=""
            - @post.post_details.each do |post_detail|
              .row
                .card-panel.hoverable
                  span.card-title
                    = post_detail.project.name
                  span
                    i.material-icons access_time
                    = "#{post_detail.spent_time} hours"
                  p
                    = post_detail.content

          #contents style=("display: none;")
            .row
              .card-panel.hoverable
                span.card-title
                  | Unknown content
                p
                  = @post.unknown_content
            .row
              .card-panel.hoverable
                span.card-title
                  | Impression content
                p
                  = @post.impression_content

          #comments style=("display: none;")  This is comment.


- if current_user.id == @post.user_id
  = link_to 'Edit', edit_me_post_path(@post)
  '|
= link_to 'Back', me_posts_path